version: '3.4'

services:
  webserver:
    container_name: server
    image: haphnium/sdc-qa:0.8
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - 5000:3000
  db:
    container_name: backend-postgres
    image: haphnium/mypostgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: qa
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'

volumes:
  pgdata:

#
# docker run \
#   -dp 5432:5432 \
#   --name dev-postgres \
#   -e POSTGRES_PASSWORD=postgres \
#   -v ${HOME}/data/postgres-data/:/var/lib/postgresql/data \
#   postgres:12.9-alpine