version: '3.4'

services:
  webserver:
    image: haphnium/sdc-qa:0.8
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGDATABASE: qa
      PGPORT: 5432
      ISDOCKER: "true"
    depends_on:
      - db
  db:
    image: haphnium/mypostgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qa
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - '5432'

volumes:
  pgdata:


# services:
#   webserver:
#     image: haphnium/sdc-qa:0.8
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 3000:3000