version: '3.4'

services:
  webserver:
    image: haphnium/sdc-qa:0.8
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGDATABASE: qa
      PGPORT: 5432
      ISDOCKER: true
    volumes:
      - ./:/usr/src/app:ro #bind mount
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    # image: haphnium/mypostgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qa
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - '5432'

volumes:
  pgdata:

#
# docker run \
#   -dp 5432:5432 \
#   --name dev-postgres \
#   -e POSTGRES_PASSWORD=postgres \
#   -v ${HOME}/data/postgres-data/:/var/lib/postgresql/data \
#   postgres:12.9-alpine